### ISSUE TITLE
Add new version on hackage to support finitary package with modern GHC

### ISSUE THREAD

**Issue by recursion-ninja** [mstksg/typelits-witnesses#9]
Currently the incredibly useful [`finitary`][0] and [`finitary-derive`][1] packages will not build with modern versions of GHC (`ghc-9.4.*`, `ghc-9.6.*`,`ghc-9.8.*`) because `finitary` depends on  [`typelits-witnesses`][2], and the most current version uploaded to Hackage, `typelits-witnesses-0.4.0.0`, does not build with modern version of GHC. \

However, `HEAD` of this repository ***does*** build with modern versions of GHC. Simply cutting a new `typelits-witnesses-0.5.0.0` release of this repository "as-is" would resolve this pernicious compatibility issue.

[0]: https://hackage.haskell.org/package/finitary
[1]: https://hackage.haskell.org/package/finitary-derive
[2]: https://hackage.haskell.org/package/typelits-witnesses

**Comment by mstksg** [comment]
cut and uploaded as `0.4.0.1` :)
